(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["blog_$slug"],{

/***/ "./src/routes/blog/[slug].svelte":
/*!***************************************!*\
  !*** ./src/routes/blog/[slug].svelte ***!
  \***************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var _components_Container_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../components/Container.svelte */ "./src/components/Container.svelte");
/* src/routes/blog/[slug].svelte generated by Svelte v3.4.4 */



const file = "src/routes/blog/[slug].svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-cy6ghe-style';
	style.textContent = "\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiW3NsdWddLnN2ZWx0ZSIsInNvdXJjZXMiOlsiW3NsdWddLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9XCJtb2R1bGVcIj5cbiAgLy8gTG9hZCB0aGUgcmVxdWVzdGVkIHBvc3QgZGF0YVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG4gIC8vIEltcG9ydCBjb250YWluZXIgY29tcG9uZW50XG4gIGltcG9ydCBDb250YWluZXIgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvQ29udGFpbmVyLnN2ZWx0ZVwiO1xuXG4gIC8vIEV4cG9ydCBwb3N0IGF0dHJpYnV0ZVxuICBleHBvcnQgbGV0IHBvc3Q7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSB7XG4gICAgbWFyZ2luOiAwO1xuICAgIG1hcmdpbi1ib3R0b206IDAuMjVyZW07XG4gIH1cblxuICAuYnlsaW5lIHtcbiAgICBjb2xvcjogIzg4ODtcbiAgfVxuXG4gIC5wb3N0LWltYWdlIHtcbiAgICBiYWNrZ3JvdW5kOiAjZWVlO1xuICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIHdpZHRoOiAxMDAlO1xuICB9XG5cbiAgLnRpdGxlIHtcbiAgICBtYXJnaW46IDJyZW0gMDtcbiAgfVxuPC9zdHlsZT5cblxuPCEtLSBTdHlsZSBlYWNoIHBvc3QgLS0+XG5cbjwhLS0gU2V0IHRoZSBwYWdlJ3MgPHRpdGxlPiBlbGVtZW50IHRvIHRoZSBwb3N0J3MgdGl0bGUgLS0+XG5cbjwhLS0gRGlzcGxheSB0aGUgcG9zdCBjb250ZW50IC0tPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiIifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	return {
		c: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		l: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		m: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"]
	};
}

function instance($$self, $$props, $$invalidate) {
	// Export post attribute
  let { post } = $$props;

	const writable_props = ['post'];
	Object.keys($$props).forEach(key => {
		if (!writable_props.includes(key) && !key.startsWith('$$')) console.warn(`<Slug> was created with unknown prop '${key}'`);
	});

	$$self.$set = $$props => {
		if ('post' in $$props) $$invalidate('post', post = $$props.post);
	};

	return { post };
}

class Slug extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-cy6ghe-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], ["post"]);

		const { ctx } = this.$$;
		const props = options.props || {};
		if (ctx.post === undefined && !('post' in props)) {
			console.warn("<Slug> was created without expected prop 'post'");
		}
	}

	get post() {
		throw new Error("<Slug>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set post(value) {
		throw new Error("<Slug>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Slug);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2Jsb2cvW3NsdWddLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0FRRTtFQUNPLE1BQUksZ0JBQUksQ0FBQyIsImZpbGUiOiI0NmE0MDc5ZTkyNDMxYjlmZmMzMC9ibG9nXyRzbHVnLmJsb2dfJHNsdWcuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IGNvbnRleHQ9XCJtb2R1bGVcIj5cbiAgLy8gTG9hZCB0aGUgcmVxdWVzdGVkIHBvc3QgZGF0YVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG4gIC8vIEltcG9ydCBjb250YWluZXIgY29tcG9uZW50XG4gIGltcG9ydCBDb250YWluZXIgZnJvbSBcIi4uLy4uL2NvbXBvbmVudHMvQ29udGFpbmVyLnN2ZWx0ZVwiO1xuXG4gIC8vIEV4cG9ydCBwb3N0IGF0dHJpYnV0ZVxuICBleHBvcnQgbGV0IHBvc3Q7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSB7XG4gICAgbWFyZ2luOiAwO1xuICAgIG1hcmdpbi1ib3R0b206IDAuMjVyZW07XG4gIH1cblxuICAuYnlsaW5lIHtcbiAgICBjb2xvcjogIzg4ODtcbiAgfVxuXG4gIC5wb3N0LWltYWdlIHtcbiAgICBiYWNrZ3JvdW5kOiAjZWVlO1xuICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIHdpZHRoOiAxMDAlO1xuICB9XG5cbiAgLnRpdGxlIHtcbiAgICBtYXJnaW46IDJyZW0gMDtcbiAgfVxuPC9zdHlsZT5cblxuPCEtLSBTdHlsZSBlYWNoIHBvc3QgLS0+XG5cbjwhLS0gU2V0IHRoZSBwYWdlJ3MgPHRpdGxlPiBlbGVtZW50IHRvIHRoZSBwb3N0J3MgdGl0bGUgLS0+XG5cbjwhLS0gRGlzcGxheSB0aGUgcG9zdCBjb250ZW50IC0tPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==